import Nav from "@/Components/Nav";
import "./globals.css";
import Foot from "@/Components/Foot";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      
    >
      <body>
        <header>
          <Nav></Nav>
        </header>
        
        <main className=" w-full mx-w-7xl p-2 md:p-4 lg:p-6">
          {children}
        </main>
        <footer>
          <Foot></Foot>
        </footer>
      </body>
    </html>
  );
}
